name: parambikulam
description: A new Flutter project.

version: 1.0.20+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  barcode_widget: ^2.0.1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.1.1
  circular_profile_avatar: ^2.0.5
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  custom_check_box: ^0.0.4
  dio: ^5.0.0
  disk_space: ^0.2.1
  equatable: ^2.0.3
  expandable: ^5.0.1
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_calendar_carousel: ^2.1.0
  flutter_html: ^2.2.1
  flutter_multi_formatter: ^2.5.1
  flutter_vibrate: ^1.3.0
  fluttertoast: ^8.0.7
  google_fonts: ^4.0.3
  group_button: ^5.2.2
  hexcolor: ^3.0.1
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  mask_text_input_formatter: ^2.1.0
  objectid: ^2.0.0
  open_file_safe: ^3.2.3
  otp_text_field: ^1.1.2
  path: ^1.8.0
  path_provider: ^2.0.9
  pdf: ^3.6.4
  percent_indicator: ^4.0.0
  permission_handler: ^10.2.0
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  quill_delta: ^3.0.0-nullsafety.2
  share: ^2.0.4
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  sn_progress_dialog: ^1.0.3
  sqflite: ^2.0.2
  wakelock: ^0.6.1+2
  badges: ^2.0.2
  qr_code_scanner: ^1.0.0
  flutter_custom_clippers: ^2.0.0
  in_app_update: ^4.0.1
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg.png
    - assets/icons/profile_pic.png
    - assets/icons/cart_icon.png
    - assets/foundation_logo.jpg
    - assets/forest_logo_black.jpg
    - assets/foundation_logo_2.jpg
    - assets/kfd.png
    - assets/kfdc.jpg
    - assets/logo_tr.jpg
    - assets/logo_tr_2.jpg
    - assets/qr_image.png
    - assets/echobag.png
    - assets/elephant2.webp
    - assets/forest.png
    - assets/ptrbg.jpg
    - assets/bgptrr.png
    
    

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/open-sans.ttf

    - family: Times
      fonts:
        - asset: assets/times-new-roman.ttf
          weight: 700
        - asset: assets/times-new-roman-grassetto.ttf

    - family: Sofia Pro
      fonts:
        - asset: fonts/Sofia Pro Bold Az.otf
          weight: 700
        - asset: fonts/Sofia Pro Light Az.otf
          weight: 300
        - asset: fonts/Sofia Pro Medium Az.otf
          weight: 400
        - asset: fonts/Sofia Pro Regular Az.otf
          weight: 500
        - asset: fonts/Sofia Pro Semi Bold Az.otf
          weight: 600
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages